### PR TITLE
Restructured with browserify

### PR DESCRIPTION
**Pull request by weswigham**
Also added three.js, physi.js, and entity.js (after modifying two of them for browserify compatibility). 3D environment should be set-upable after this.

Oh, also moved plane.html to be hosted from `/control`. Because control.

### CODE REVIEW

**Comment by JRJurman** [comment]
I think the point of the plane.html was that there would be a turret.html, with a different set of controls (one that gravitates towards the center)... I haven't had a chance to look though the code, but I kinda like the idea of different control styles...

**Comment by weswigham** [comment]
Is there any reason those wouldn't be submodule in the same controller client? The html certainly doesn't change (or at least not much?).

**Comment by JRJurman** [comment]
Could we create two unique end-points? I imagined we'd have just a page where a user could simple click on a picture of a spaceship, or a picture of a turret, to end up in different points...

**Comment by weswigham** [comment]
But why would those be separate endpoints? They need to share 90% of their codebase anyway, and the client initiates the controller session anyway.

**Comment by JRJurman** [comment]
Ahhhhh, okay... Good point... :cake: 
Looking at the overall commit and the move from plane.html to it's own folder, actually makes sense, and I give it my :+1:

**Pull request merged**
