### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by JRJurman**
You should totally merge this in!

### CODE REVIEW

**Comment by evajurman** [comment]
you don't need to make SUCH SILLY MERGE REQUESTS

**Comment by JRJurman** [comment]
IT'S IMPORTANT!

**Comment by evajurman** [comment]
:+1:

**Comment by JRJurman** [comment]
:cake:

**Comment by weswigham** [comment]
Merge request all the things

**Comment by evajurman** [comment]
I'm learnning

**Pull request merged**
